import matplotlib.pyplot as plt
weeks = ['Week 1', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6', 'Week 7', 'Week 8']
money = [200, 250, 300, 350, 400, 450, 500, 550]
plt.plot(weeks,money)
plt.show()
plt.title('My Savings Progress Chart')
plt.xlabel('Weeks of 2 Months')
plt.ylabel('Savings Amount (₹)')
plt.grid(True)
plt.ylim(0, 600)
plt.show()
plt.plot(weeks,money, color='cyan', marker='o', linestyle='dashed', linewidth=5)
plt.title('My Savings Progress Chart')
plt.xlabel('Weeks of 2 Months')
plt.ylabel('Savings Amount (₹)')
plt.grid(True)
plt.ylim(0, 600)
plt.show()
plt.bar(weeks, money, color='light green')
plt.title('My Savings Progress Chart')
plt.xlabel('Weeks of 2 Months')
plt.ylabel('Savings Amount (₹)')
plt.ylim(0, 600)
plt.show()