print ("Input the amount of Marks obtained out of 100")
maths = int(input("Maths: "))
science = int(input("Science: "))
english = int(input("English: "))
hindi = int(input("Hindi: "))
sum = ( maths + science + english + hindi )
percentage = (sum/400)*100
print ("Total marks obtained is")
print (sum)
print ("Percentage of marks obtained is")
print (percentage)